### ISSUE TITLE
The connection is not persistent

### ISSUE THREAD

**Issue by payerus** [anthemtotheego/C_Shot#1]
Thank you for providing this program, but I have a problem. After I execute it, my meterpreter can receive the session, but it will be disconnected in only one or two seconds. The injection I used is itself. Looking forward to your reply
![image](https://user-images.githubusercontent.com/44284221/89025980-70ba5b00-d35a-11ea-98fc-30481df37acc.png)
![image](https://user-images.githubusercontent.com/44284221/89026002-7f087700-d35a-11ea-8859-5f66ce698aa0.png)

**Comment by manasmbellani** [comment]
@DshSec  That is unusual - what OS, version, SP, etc did you try this on? I had no issue running the compiled binary on a Win 7 SP1  machine without an AV.

Also, did you have Win defender, AV or any other host-based IDS running at the same time ? I have seen Meterpreter conns break before due to blocks from AV.

**Comment by payerus** [comment]
I tested it on two systems，WIndows7  professional edition  Service Pack 1 Build 7601 and Microsoft Windows 10 professional edition   Build 19041 ,windows7 no security software is installed,windows10  has installed huorong safety software,I don't think the security software blocked it because I didn't receive any messages and the security software didn't record anything，When I executed on win7, the program stopped working，When I executed on win7, the program stopped working, but meterpreter received the session, which was still not persistent, and was disconnected in a second or two。

**Comment by anthemtotheego** [comment]
Hi DshSec, thanks for the feedback and using the tool!  This issue is usually caused 99% of the time by AV/EDR.  It appears you are getting execution but something is killing your connection shortly after.  This would be caused either by an issue with your bin file you are trying to execute or as mentioned above some 3rd party interference like AV/EDR.  Double check that the architecture of the tool matches that of your bin, example x86 Meterpreter bin is executed by x86 version of C_Shot.  You can also test by using the parent spoofing option as well and see if you can get a solid connection back.  Best bet would be to re-walk through your setup and double check everything is correct.   I don't believe this is a tooling issue but will reopen if more people experience the problem.  Thanks.
